version: '3.8'

services:
  # # File Server (starts first as it's needed by others)
  # file-server:
  #   build: ./mcp/calendar
  #   container_name: file-server
  #   ports:
  #     - "3030:3030"
  #   networks:
  #     - app-network
  #
  # BrightData Agent Server (second in startup order)
  brightdata-agent:
    build: ./brightdata_agent_server
    container_name: brightdata-agent
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BROWSER_AUTH=${BROWSER_AUTH}
      - API_TOKEN=${API_TOKEN}
      - WEB_UNLOCKER_ZONE=${WEB_UNLOCKER_ZONE}
    networks:
      - app-network

  # MCP Service (third in startup order)
  mcp:
    build: ./mcp
    container_name: mcp-service
    ports:
      - "3002:3002"
      - "3030:3030"  # Add port mapping for file server
    environment:
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - BRIGHTDATA_AGENT_URL=http://brightdata-agent:5000
      - FILE_SERVER_URL=http://localhost:3030  # Point to localhost since both servers run in same container
    depends_on:
      - brightdata-agent
    networks:
      - app-network

  # Agent Service (fourth in startup order)
  agent:
    build: ./agent
    container_name: agent-service
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BROWSER_AUTH=${BROWSER_AUTH}
      - API_TOKEN=${API_TOKEN}
      - WEB_UNLOCKER_ZONE=${WEB_UNLOCKER_ZONE}
      - TRAVELGENIE_MCP_URL=http://mcp:3002
    depends_on:
      - mcp
    networks:
      - app-network

  # Client Service (last in startup order)
  client:
    build: ./client
    container_name: client-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AGENT_URL=http://agent:8000
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}
    depends_on:
      - agent
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
